### ISSUE TITLE
WicketBootSecuredWebApplication should not setAuthorizationStrategy()

### ISSUE THREAD

**Issue by mweirauch** [MarcGiffing/wicket-spring-boot#101]
I was scratching my head why the following didn't work and was still shown allthough not authenticated as "ADMIN".
```
MetaDataRoleAuthorizationStrategy.authorize(adminLabel, RENDER, Roles.ADMIN);
```
It turns out `WicketBootSecuredWebApplication.init()` sets the authorization strategy to `AnnotationsRoleAuthorizationStrategy` whereas some instructions before the `wicket-auth-roles` `AuthenticatedWebApplication` sets the authorization strategy to the more convenient `RoleAuthorizationStrategy` which allows for annotation- and metadata-based role assignments.
Is there any reason for the `WicketBootSecuredWebApplication` switching to annotation-based role support only?
Currently I have to roll out a custom config to circumvent this:
```
@ApplicationInitExtension
public class WicketConfig implements WicketApplicationInitConfiguration {

    @Override
    public void init(WebApplication webApplication) {
        webApplication.getSecuritySettings().setAuthorizationStrategy(
                new RoleAuthorizationStrategy((AuthenticatedWebApplication) webApplication));
    }

}
```

**Comment by MarcGiffing** [comment]
There is no reason. I wasn't aware of it. :) I've removed it from the WicketBootSecuredWebApplication class. Thanks for the issue!

**Comment by mweirauch** [comment]
Thanks!
