### ISSUE TITLE
@SpringBean not working from Wicket Pages

### ISSUE THREAD

**Issue by ChambreNoire** [MarcGiffing/wicket-spring-boot#106]
Hi,
I have a MailServiceImpl @Service which implements MailService. Despite it being correctly instantiated, with its JavaMailSender etc. injecting it into Wicket pages via @SpringBean just yields null.
Any ideas?
Thanks,
CN

**Comment by martin-g** [comment]
Show us some code please!

**Comment by MarcGiffing** [comment]
Please take a look at the examples https://github.com/MarcGiffing/wicket-spring-boot-examples.
Are you extendingthe default WicketApplication class?

**Comment by MarcGiffing** [comment]
And please check that you are using the latest verdion 1.0.7 https://github.com/MarcGiffing/wicket-spring-boot/issues/102

**Comment by ChambreNoire** [comment]
Sorry! Unbelievably stupid mistake. Somehow I hadn't noticed that in overriding init(), super.init() hadn't been called! Case closed! Delete the issue. Burn the hard drive. ;-)
Thanks all the same!
