### ISSUE TITLE
@WicketSignInPage not working

### ISSUE THREAD

**Issue by ChambreNoire** [MarcGiffing/wicket-spring-boot#108]
Hi,
I have two pages, one annotated @WicketHomePage and the other @WicketSignInPage. However despite not being logged in, Wicket systematically renders the HomePage. Any ideas? Here's my config. Maybe I'm missing something in my yaml? 

    @Component
    public class WicketConfig extends WicketBootSecuredWebApplication {

        @Override
        protected Class<? extends AbstractAuthenticatedWebSession> getWebSessionClass() {
            return WicketSession.class;
        }
        ...
    }

and

    public class WicketSession extends AuthenticatedWebSession {

        public WicketSession(final Request request) {
            super(request);
        }

        @Override
        protected boolean authenticate(String s, String s1) {
            return false;
        }
    }

Thanks

**Comment by martin-g** [comment]
A page should be annotated with `@AuthorizeInstantiation` to be protected. In this case Wicket will redirect to the sign in page.

**Comment by MarcGiffing** [comment]
I've never tested the security configuration without spring security or shiro. https://github.com/MarcGiffing/wicket-spring-boot-examples/tree/master/spring-security . If the solution  martin provided is not working than its a configuration problem of this project...
