### ISSUE TITLE
BeanValidationConfig should provide ValidatorProvider based on SpringConstraintValidatorFactory

### ISSUE THREAD

**Issue by eximius313** [MarcGiffing/wicket-spring-boot#112]
```com.giffing.wicket.spring.boot.starter.configuration.extensions.external.beanvalidation.BeanValidationConfig``` configures the Application using ```org.apache.wicket.bean.validation.DefaultValidatorProvider``` which doesn't know anything about Spring conetxt, and doesn't autowire Beans inside Validators (which is a bug).
Instead it should provide custom ```Supplier<Validator>``` which returns ```Validator``` that uses ```org.springframework.validation.beanvalidation.SpringConstraintValidatorFactory```

Showcase:
[wicket-showcase-validatorAutowire.zip](https://github.com/MarcGiffing/wicket-spring-boot/files/1068664/wicket-showcase-validatorAutowire.zip)

Steps to reproduce:
1)Run ./gradlew bootRun
2)Go to http://localhost:8080/createUser?login=NotOccupied&name=MyName&email=test@test.com and observe console -> User will be "created"
3)Go to http://localhost:8080/createUser?login=Occupied&name=MyName&email=test@test.com -> and observe console -> Validation error will be shown
4)Go to http://localhost:8080 click "Add user" and type Occupied, MyName, test@test.com. Click save and observe console -> Exception is thrown

**Comment by MarcGiffing** [comment]
Hey, 
I've got the exception that the resource add.user doesn't exists...after adding a default UserPage.properties instead of the UserPage_pl.utf8.properties the exception is gone. What is the exception you've got?

**Comment by eximius313** [comment]
NPE, because ```@Autowired``` annotation is being ignored by ```DefaultValidatorProvider```

**Comment by MarcGiffing** [comment]
Can you post the stacktrace?

**Comment by eximius313** [comment]
1)Unzip the [showcase](https://github.com/MarcGiffing/wicket-spring-boot/files/1068664/wicket-showcase-validatorAutowire.zip)
2)Change UserPage_pl.utf8.properties to UserPage.utf8.properties (sorry!)
3)cd wicket-showcase
4)./gradlew bootRun
5)go to http://localhost:8080
6)Click Add User
7)type "Occupied" without quotes to login field
8)type "MyName" to name field
9)type "test@test.com" in email field
10)click "Save"
I just checked it and it throws:
```
Caused by: java.lang.NullPointerException: null
        at com.showcase.validation.UniqueFieldValidator.isValid(UniqueFieldValidator.java:55) ~[main/:na]
```
because ```@Autowire``` field is not autowired

**Comment by MarcGiffing** [comment]
You can use Wickets Injector:
https://ci.apache.org/projects/wicket/apidocs/7.x/org/apache/wicket/injection/Injector.html

~~~~~ java
import org.apache.wicket.injection.Injector;
import org.apache.wicket.spring.injection.annot.SpringBean;

    @SpringBean
    private UserRepository repository;
    
    public UniqueFieldValidator() {
	    Injector.get().inject(this);
    }

~~~~~

You can also remove the @ Component annotation...

**Comment by eximius313** [comment]
JSR303 just like Entities belong to data layer not to frontend. 
Including the whole Wicket library for just one annotation would be odd.
Not even mentioning that other projects that use this entity doesn't use Wicket.

**Comment by MarcGiffing** [comment]
Can you provide an example project? I've now clue how to configure the SpringConstraintValidatorFactory to get it work. I've tried different configuration found on stackoverflow but without luck.

**Comment by eximius313** [comment]
And what is wrong with the project and guidelines that I provided in [this comment](https://github.com/MarcGiffing/wicket-spring-boot/issues/112#issuecomment-316501730) ?
What should I change?

**Comment by MarcGiffing** [comment]
I mean the solutiin...I don't know how to fix this.

**Comment by MarcGiffing** [comment]
OK, b873861 overrides the getValidator methods and set the existing validator bean.

The problem is that hibernate also sets the validator so that you still got an NPE. You have to disable hibernates validation:
~~~~
spring.jpa.hibernate.javax.persistence.validation.mode=none
~~~~

**Comment by eximius313** [comment]
Wow! That was tricky! I'm happy you made it! Congrats and Thank you ;)
(Ps. sorry I didn't understand what you ment by "project" in previous comment)

**Comment by eximius313** [comment]
By the way - If Hibernate fires it's own validator without wiring the beans, then how it is possible that this works fine when using Spring's Controller: ``` http://localhost:8080/createUser?login=Occupied&name=MyName&email=test@test.com``` ?

**Comment by MarcGiffing** [comment]
> By the way - If Hibernate fires it's own validator without wiring the beans, then how it is possible that this works fine when using Spring's Controller: http://localhost:8080/createUser?login=Occupied&name=MyName&email=test@test.com ?

Maybe this explains it a little bit...
https://stackoverflow.com/a/2728802/3972310

**Comment by eximius313** [comment]
But still - this is exactly the same project, the same Entity, I don't set ```<validation-mode>NONE</validation-mode>``` nor ```javax.persistence.validation.mode=none``` and Spring's Controller: http://localhost:8080/createUser?login=Occupied&name=MyName&email=test@test.com works fine. 
Maybe SprintBoot sets these properties, but then it should work with Wicket as well
A mystery :)
I'll try it with 1.0.10 when you release it
