### ISSUE TITLE
synchronise wicket versions between wicket-bootstrap-core and wicket-spring-boot-starter-parent

### ISSUE THREAD

**Issue by braunimmobilien** [MarcGiffing/wicket-spring-boot#113]
i am not able to find versions of wicket-bootstrap-core and wicket-spring-boot-starter-parent which share the same wicket version.

**Comment by mweirauch** [comment]
From the `wicket-spring-boot` README we know that version `1.x.x` is for Wicket `7.x.x`. From `wicket-bootstrap` README we know that `0.10.x` is for Wicket `7.x.x`.

What's so difficult figuring that out? E.g. there's the Eclipse POM editor which has a nice dependency hierarchy tab.

Here's a version matrix and dependency excerpt from one of my projects pom.xml:
```
<properties>
    ...
    <wicket-spring-boot.version>1.0.8</wicket-spring-boot.version>
    <wicket-bootstrap.version>0.10.14</wicket-bootstrap.version>
    <wicket.version>7.7.0</wicket.version>
    ...
</properties>

...

<dependency>
    <groupId>com.giffing.wicket.spring.boot.starter</groupId>
    <artifactId>wicket-spring-boot-starter</artifactId>
    <version>${wicket-spring-boot.version}</version>
</dependency>
<dependency>
    <groupId>de.agilecoders.wicket</groupId>
    <artifactId>wicket-bootstrap-core</artifactId>
    <version>${wicket-bootstrap.version}</version>
</dependency>
<dependency>
    <groupId>de.agilecoders.wicket</groupId>
    <artifactId>wicket-bootstrap-themes</artifactId>
    <version>${wicket-bootstrap.version}</version>
</dependency>
<dependency>
    <groupId>org.wicketstuff</groupId>
    <artifactId>wicketstuff-annotation</artifactId>
    <version>${wicket.version}</version>
</dependency>
<dependency>
    <groupId>org.apache.wicket</groupId>
    <artifactId>wicket-devutils</artifactId>
    <version>${wicket.version}</version>
</dependency>
```

**Comment by martin-g** [comment]
> i am not able to find versions of wicket-bootstrap-core and wicket-spring-boot-starter-parent which share the same wicket version.

@braunimmobilien Usually it is good to tell us what you have tried, i.e. which versions.
See what @mweirauch suggested. This should work! If it doesn't then please paste the error here!

**Comment by MarcGiffing** [comment]
I've added this check to reveal version problems. Also on the same baseline (1.7.x) yoe can have different versions. Each project (wicket spring boot or wicket bootstrap) updates the base version on its on....and the user can also add a version. The eception should reveal this problem so that you have to manage the version on your own.

**Comment by braunimmobilien** [comment]
Thank you Marc this reveals the situation in this version jungle

2017-06-14 12:19 GMT+02:00 MarcGiffing <notifications@github.com>:

**Comment by MarcGiffing** [comment]
You will have with each big library/project problems which uses multiple modules. It's always a good idea to check all versions of all dependencies after changing a version or adding a dependency.

https://github.com/MarcGiffing/wicket-spring-boot/issues/99#issuecomment-307685336
https://github.com/MarcGiffing/wicket-spring-boot/issues/104#issuecomment-297479668
