### ISSUE TITLE
Security Settings exclude page

### ISSUE THREAD

**Issue by vaskomichal** [MarcGiffing/wicket-spring-boot#119]
How to exclude page from security in spring security wicket lib?

**Comment by MarcGiffing** [comment]
Please use Stackoverflow or the the Wicket Mailing list for general questions which are not related to this project.

* https://stackoverflow.com/
* http://apache-wicket.1842946.n4.nabble.com/Users-forum-f1842947.html

You should also describe in detail how your project is configured (example code/configuration), how it currently behaves and what you expect.
