### ISSUE TITLE
ApplicationContext not available during tests

### ISSUE THREAD

**Issue by eximius313** [MarcGiffing/wicket-spring-boot#120]
Here is the quickstart application (using maven, not gradle :D) [showcase-applicationContext.zip](https://github.com/MarcGiffing/wicket-spring-boot/files/1302889/showcase-applicationContext.zip)

1) When you run the app (```WicketApplication``` as SpringBoot application), and navigate to ```localhost:8080``` you will see, that ApplicationContext is available and link is enabled
2) When you run the test, you'll see that although ```ApplicationContext``` is being injected into test, it is not being available in ```WicketApplication```

By the way - why when I try to use:
```
@SpringBean
private ApplicationContext applicationContext;
```
it throws exception, and we must use this ugly hack: ```WicketApplication.getWicketApplication().getApplicationContext()```?

**Comment by MarcGiffing** [comment]
I've created a normal component and injected it successfully.

https://stackoverflow.com/questions/9823225/injecting-applicationcontext-into-wicket-component-with-springbean-fails

Is it a general problem with all beans?

**Comment by eximius313** [comment]
@MarcGiffing 
First of all, the soulution that is provided in your link I'm explicitly quoting in my issue:
> we must use this ugly hack: WicketApplication.getWicketApplication().getApplicationContext()?

Second, I've never say anything about injecting "normal components"... 
The problem is with ApplicationContext during test run, so please run the test from my application and you will immediately see what's wrong.

**Comment by MarcGiffing** [comment]
OK, then please look at the sample project:

https://github.com/MarcGiffing/wicket-spring-boot-examples/blob/master/simple/src/test/java/com/giffing/examples/wicket/spring/boot/simple/HomePageTest.java

You have to set the applicationContext:
`ReflectionTestUtils.setField(wicketApplication, "applicationContext", applicationContextMock);`

Then remove the getApplicationContext method from your WicketApplication class.

**Comment by eximius313** [comment]
> You have to set the applicationContext:
ReflectionTestUtils.setField(wicketApplication, "applicationContext", applicationContextMock);

I've done that as well (I just removed that when I was cleaning the code before I uploaded it here)
It doesn't change anything:
1) ```WicketApplication.get().getApplicationContext()``` is still null
2) ```@SpringBean private ApplicationContext applicationContext;``` still throws Exception.

Here you have showcase with ```ReflectionTestUtils```: [showcase-applicationContext.zip](https://github.com/MarcGiffing/wicket-spring-boot/files/1320658/showcase-applicationContext.zip)

**Comment by MarcGiffing** [comment]
Have you removed the method wicketApplication class? I've run the test sucessully. Sorry I can't check the project now(mobile).

**Comment by eximius313** [comment]
@MarcGiffing, I don't understand.... 
```WicketApplication.getWicketApplication()``` is just a shortcut for: ```((WicketApplication)WicketApplication.get())``` so I don't know what removing it, was suppose to change.

And in my Component I MUST have access to ```ApplicationContext```, so until you fix Exception with ```@SpringBean private ApplicationContext applicationContext``` how else can I get it if not using ```getApplicationContext()``` ?

**Comment by MarcGiffing** [comment]
You have to remove the getApplicationContext from your WicketApplication class. You're overriding the method from the super class which holds the aplication context in a variable. Instead of using the @SpringBean annotation you can simple access the application context with WicketApplication.getWicketApplication().getApplicationContext().

**Comment by eximius313** [comment]
Ok, now I get it.
So method from the first link that you have provided is wrong - we must not use ```WebApplicationContextUtils```.

Now, would you agree with me, that providing ```ApplicationContext``` by```@SpringBean``` would be consistent with the rest of application and most convenient solution (and we could avoid searching for the incorrect, as it occurred, solutions from StackOverflow)?
If yes - can I fill a feature request?

**Comment by MarcGiffing** [comment]
I think the problem isn't related to this project. You can create an issue in Wickets Jira.
https://issues.apache.org/jira/projects/WICKET/issues

The classes SpringComponentInjector / AnnotProxyFieldValueFactory could be extended return the application context if requested without searching for a bean.

**Comment by eximius313** [comment]
Ok, thanks. And one question about this ```ReflectionTestUtils```:
If you start regular application, then ```ApplicationContext``` is being injected into ```WicketApplication``` through ```@Autowire```. Why in Tests, we must use ```ReflectionTestUtils```? Why ```@Autowire``` doesn't work there?

**Comment by martin-g** [comment]
The real problem is that `applicationContext.getBean(ApplicationContext.class)` doesn't find the bean.
You should ask Spring people why this is like this.
They recommend using `ApplicationContextAware` interface when you need it.
As @MarcGiffing suggested Wicket can return the WebApplicationContext directly. But this will work only in runtime, not in tests.

**Comment by MarcGiffing** [comment]
@eximius313 thats a good question. I think the ReflectionTestUtils is currently not needed anymore. Maybe an remnant from previous versions....

I think it doesn't find the ApplicationContext cause its not a real bean. Maybe they also implemented a workaround to support @Autowired but I couldn't find a hint in the Spring sources.
