### ISSUE TITLE
Please Upgrade to SpringBoot-2.0.0

### ISSUE THREAD

**Issue by haruki869** [MarcGiffing/wicket-spring-boot#131]
Dear @MarcGiffing 
SpringBoot-2.0.0 is now released.
Could you please upgrade?

Sincerely,
Haruki Ueno

**Comment by MarcGiffing** [comment]
I think I'll only update the Wicket 8 branch to Spring Boot 2

**Comment by haruki869** [comment]
Thank you so much for your work!
I'll upgrade immediately.
