### ISSUE TITLE
spring boot 2 support

### ISSUE THREAD

**Issue by mdeanda** [MarcGiffing/wicket-spring-boot#140]
it would be nice to get this to work for spring boot 2

**Comment by martin-g** [comment]
See https://github.com/MarcGiffing/wicket-spring-boot/pull/139#issuecomment-398687432

**Comment by mdeanda** [comment]
ah, i managed to get the example app to work if i switch to that branch. i'll see if i can get a stand alone app to work as well while not from the cloned project. thanks!
