### ISSUE TITLE
Upgrade Wicket to 8.2.0

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#146]

**Comment by MarcGiffing** [comment]
> Last cause: A Cookie name can not be null or empty
WicketMessage: Exception in rendering component: [HtmlHeaderContainer [Component id = _header_]]

> Root cause:
java.lang.IllegalArgumentException: A Cookie name can not be null or empty
     at org.apache.wicket.util.cookies.CookieUtils.getSaveKey(CookieUtils.java:188)
     at org.apache.wicket.util.cookies.CookieUtils.getCookie(CookieUtils.java:232)
     at org.apache.wicket.protocol.ws.api.BaseWebSocketBehavior.getSessionId(BaseWebSocketBehavior.java:177)
     at org.apache.wicket.protocol.ws.api.BaseWebSocketBehavior.renderHead(BaseWebSocketBehavior.java:128)
     at org.apache.wicket.Component.internalRenderHead(Component.java:2641)
     at org.apache.wicket.markup.renderStrategy.AbstractHeaderRenderStrategy.renderRo...


> Complete stack:
org.apache.wicket.WicketRuntimeException: Exception in rendering component: [HtmlHeaderContainer [Component id = _header_]]
     at org.apache.wicket.Component.internalRenderComponent(Component.java:2503)
     at org.apache.wicket.MarkupContainer.onRender(MarkupContainer.java:1592)
     at org.apache.wicket.Component.internalRender(Component.java:2287)
     at org.apache.wicket.Component.render(Component.java:2218)
     at org.apache.wicket.MarkupContainer.renderNext(MarkupContainer.java:1453)

**Comment by MarcGiffing** [comment]
https://issues.apache.org/jira/browse/WICKET-6593
https://issues.apache.org/jira/browse/WICKET-6571

**Comment by geramaya** [comment]
Hey,
what is the status about upgrade to wicket 8.1 and 8.2 on wicket-spring-boot?

**Comment by martin-g** [comment]
Hi,

I broke Wicket-Native-WebSocket 8.1.0 so I will give you few workarounds.

1) You can use Wicket Core 8.1.0 but with Wicket-Native-WebSocket 8.0.0, i.e. you have to pin w-n-WebSocket to 8.0.0 in your dependency management tool (Maven, Gradle, SBT, ...).
Once Wicket 8.2.0 is released you can remove this workaround.

2) In your web.xml set the session cookie name explicitly. This will workaround the problem in Tomcat. The cookie name must be JSESSIONID so that all your user sessions are preserved in case you do a rolling upgrade.

Wicket Spring Boot itself doesn't depend on anything specific in Wicket 8.1.0 and since 8.1.0 is binary compatible to 8.0.0 it should still work without any problems.

**Comment by eximius313** [comment]
@martin-g do you know when Wicket 8.2.0 will be released?

**Comment by jmewes** [comment]
Wicket 8.2.0 has been released today.

http://wicket.apache.org/news/2018/11/17/wicket-8.2.0-released.html

**Comment by MarcGiffing** [comment]
You shouldn't use the Wicket Spring Boot Starter as a parent pom(maven). Use Spring Boot as a parent pom. You can change the Wicket version without waiting for a release here. The version upgrades should detect compatibility problems with Spring Boot and/or Wicket.

But I'll make a new release later today.

**Comment by MarcGiffing** [comment]
Can't deploy to nexus:
Unhandled: java.io.IOException: No space left on device

Does someone know how to skip a specific module when using the maven release plugin? The example project is to big...but I can't skip it from the release process.

**Comment by martin-g** [comment]
You should add :
```
<configuration>
  <skip>true</skip>
</configuration>
```
to maven-deploy-plugin

**Comment by MarcGiffing** [comment]
Doesn't work. I've also tried
```
<plugin>
	<groupId>org.apache.maven.plugins</groupId>
	<artifactId>maven-release-plugin</artifactId>
	<version>2.5.3</version>
	<executions>
		<execution>
			<phase>none</phase>
		</execution>
	</executions>
</plugin>
```

release successful with examples project...
