### ISSUE TITLE
SecureWebSession sets invalid SPRING_SECURITY_CONTEXT_KEY

### ISSUE THREAD

**Issue by zbynekvavros** [MarcGiffing/wicket-spring-boot#150]
The [SecureWebSession](https://github.com/MarcGiffing/wicket-spring-boot/blob/master/wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/configuration/extensions/external/spring/security/SecureWebSession.java) sets Spring Security into session upon successful authentication. But since this is done via [org.apache.wicket.session.HttpSessionStore#setAttribute()](https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/session/HttpSessionStore.java) that prefixes all attribute names the resulting property key is actually "wicket:wicket-filter:SPRING_SECURITY_CONTEXT". And of course the [HttpSessionSecurityContextRepository](https://github.com/spring-projects/spring-security/blob/master/web/src/main/java/org/springframework/security/web/context/HttpSessionSecurityContextRepository.java) can't read that property. Is this intended behavior?

**Comment by zbynekvavros** [comment]
I added attribute to raw session in my login form for now (since I don't want to extend the `SecureWebSession` yet) :

    final HttpServletRequest servletRequest = (HttpServletRequest) RequestCycle.get().getRequest().getContainerRequest();
    final HttpSession httpSession = servletRequest.getSession(false);
    httpSession.setAttribute(HttpSessionSecurityContextRepository.SPRING_SECURITY_CONTEXT_KEY, SecurityContextHolder.getContext());

and its working fine.

**Comment by MarcGiffing** [comment]
OK, I've tested it with the example application. There is no need to set the http session attribute at all. It will be automatically setted in HttpSessionSecurityContextRepository line 374. 
@zbynekvavros Is there a currently a real problem or are you confused about the wrong attribute setting in the SecureWebSession?

**Comment by zbynekvavros** [comment]
Well I know there is no reason unless you have my setup:
I'm setting Spring Security's [invalidSessionUrl](https://github.com/spring-projects/spring-security/blob/5c2ee09bc3a0fe0a14b0aa86d1946542c4ca2aab/config/src/main/java/org/springframework/security/config/annotation/web/configurers/SessionManagementConfigurer.java#L129)  to my login page (so user gets redirected to login when session expires). Unfortunately even the new session in Spring is considered invalid so whenever user accesses login for the first time they see my message "session  expired". To handle this I moved my login page to [ignoring](https://github.com/spring-projects/spring-security/blob/5c2ee09bc3a0fe0a14b0aa86d1946542c4ca2aab/config/src/main/java/org/springframework/security/config/annotation/web/builders/WebSecurity.java#L158) section in my security config. And because of this the HttpSessionSecurityContextRepository is not invoked at all. I don't think this behavior is a problem at all... Probably all cause my "special" case.

**Comment by MarcGiffing** [comment]
OK, I'll fix the wrong session attribute setting.
