### ISSUE TITLE
Upgrade to latest Wicket 8.6.x version

### ISSUE THREAD

**Issue by tdziurko** [MarcGiffing/wicket-spring-boot#161]
Is it planned to bump dependencies to the latest 8.6.1 version of Apache Wicket and libraries around it?

**Comment by tdziurko** [comment]
I can prepare a PR if needed :)

**Comment by MarcGiffing** [comment]
I'll release a new version if you provide a pull request but take also a look at #148

**Comment by tgoetz** [comment]
I created a PR for this (Spring Boot upgrade also included): https://github.com/MarcGiffing/wicket-spring-boot/pull/162

**Comment by MarcGiffing** [comment]
It seems like dependency issue. The tests of the example project failing:
java.lang.NoClassDefFoundError: Could not initialize class net.minidev.json.JSONValue

Or am I wrong?

**Comment by tgoetz** [comment]
I can take a look at this ...

**Comment by tgoetz** [comment]
All tests are green for me when running them locally. Could you provide a complete stacktrace if you still experience that exception?
