### ISSUE TITLE
Unable to change configuration-type when using devtools

### ISSUE THREAD

**Issue by abiuan** [MarcGiffing/wicket-spring-boot#170]
Hello,
I saw that wicket starter forces configuration-type to DEVELOPMENT when devtools starter is activated, and I'm unable to change it.
The change of configuration-type to DEPLOYMENT could be useful when testing CSS, for example, when wicket tags can be disturbing.

Regards

**Comment by MarcGiffing** [comment]
Is it OK to disable the property setting with
wicket.spring.devtools.restart.enabled = false

**Comment by abiuan** [comment]
Hello,

"wicket.spring.devtools.restart.enabled" is not a recognized property.

Did you mean "spring.devtools.restart.enabled"? Using this property automatic
restart of the embedded tomcat is disabled (that is what I do not want) but
wicket tags are still present even if
"wicket.core.settings.general.configuration-type" is set to DEPLOYMENT.

Regards

Alberto

P.S.
I'm using wicket-spring-boot version 3.0.3-RC.

**Comment by MarcGiffing** [comment]
Its not yet released. I've commited it in the Wicket 8 branch. See my commit in this ticket.
