### ISSUE TITLE
How do I add additional, custom filters?

### ISSUE THREAD

**Issue by jhamsle** [MarcGiffing/wicket-spring-boot#177]
I'd like to add an additional filter to better integrate with Elastic using [this](https://gist.github.com/mdindoffer/21d61433e1cd2b3c23c5880c76a11713) as a model.  Normally I would have modified the **web.xml** file, but since these things are now auto-configured I'm not sure how I go about registering a new listener.  Wicket itself doesn't seem to allow it via code; do I need to create a custom config initializer?

**Comment by jhamsle** [comment]
I'm open to alternatives, but I was able to achieve this by registering a FilterRegistrationBean that creates my new filter.  If I get no suggestions by the end of the week I'll close this issue.

**Comment by martin-g** [comment]
Actually, this is the correct way for a Spring Boot application.

**Comment by jhamsle** [comment]
Good deal then.  Thanks for letting me know.
