### ISSUE TITLE
Spring boot 2.6.1: circular reference

### ISSUE THREAD

**Issue by saraminto** [MarcGiffing/wicket-spring-boot#183]
Hello, 

I'm trying to run wicket spring boot project with spring boot 2.6.1, but I get

> ***************************
> APPLICATION FAILED TO START
> ***************************
> Description:
> The dependencies of some of the beans in the application context form a cycle:
>    wicketextensionApplicationSettingsConfig (field private com.giffing.wicket.spring.boot.starter.app.classscanner.candidates.WicketClassCandidatesHolder com.giffing.wicket.spring.boot.starter.configuration.extensions.core.settings.application.ApplicationSettingsConfig.holder)
> ┌─────┐
> |  com.giffing.wicket.spring.boot.starter.app.classscanner.ClassCandidateScanner
> └─────┘
> Action:
> Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

Is it possible to fix this inconvenience?

**Comment by geramaya** [comment]
wow, this was fast! great job! :)

Am 12.12.2021 um 22:05 schrieb MarcGiffing:

**Comment by reckart** [comment]
Any idea why 3.1.0 is not yet on Maven Central?

**Comment by reckart** [comment]
Never mind, found the reason: https://github.com/MarcGiffing/wicket-spring-boot/issues/184

**Comment by MarcGiffing** [comment]
Please use 3.1.5. I hope it is available soon in Maven Central.
