### ISSUE TITLE
upgrade project to spring boot 2.6.2

### ISSUE THREAD

**Issue by saraminto** [MarcGiffing/wicket-spring-boot#187]
older versions of spring boot (up to 2.6.2) have a dependency on vulnerable log4j2 library version, but
after the release of 2.6.2 spring boot updated its dependency of log4j2 dependency to 2.17.0 version.
Could you, please, upgrade wicket-spring-boot version to use spring boot dependency 2.6.2?

**Comment by mskopp** [comment]
Let's go to spring boot 2.6.3 - I have a gradle wicket-spring-boot 3.1.6 project already running with 2.6.3 (2.6.1 overwritten by gradle config) nicely.

**Comment by mskopp** [comment]
Update:
works nicely with spring boot 2.6.5 and also with Wicket 9.9.0

	id 'org.springframework.boot' version '2.6.5'
