### ISSUE TITLE
Upgrade to Spring Boot 3.2 and Wicket 10 and Java 17 

### ISSUE THREAD

**Issue by geramaya** [MarcGiffing/wicket-spring-boot#196]
Hey all,

What's the plan or roadmap for wicket-spring-boot and apache wicket with spring-boot 3.0 and Java 17? Exists some planning versions/dates for the new releases?

**Comment by martin-g** [comment]
Spring 6.x uses jakarta.** APIs.
Wicket 10.x depends on the following to be able to make a release:
https://cwiki.apache.org/confluence/display/WICKET/Migration+to+Wicket+10.0#MigrationtoWicket10.0-TODO

The best you can do it to vote for these issues by adding a comment!

**Comment by pogurek** [comment]
I was about to ask the same question. Nice to hear that this project is alive. As I understand the only blocker to upgrade this project to Spring Boot 3 now is the jakarta API thing. So once the Wicket 10 is released I'm willing to help with this project as far as my abilities allow.

**Comment by MarcGiffing** [comment]
I've prepared a branch for Wicket 10:
https://github.com/MarcGiffing/wicket-spring-boot/tree/wicket-10

**Comment by ilgrosso** [comment]
Nice job!
Are the 4.0.0-SNAPSHOT artifacts from the new `wicket-10` branch published somewhere?

**Comment by ilgrosso** [comment]
@MarcGiffing thanks for merging #198 !
Can you publish the `4.0.0-SNAPSHOT` artifacts from current `wicket-10` branch to OSS Sonatype?

**Comment by martin-g** [comment]
+1 for 4.0.0-SNAPSHOT from me too!

**Comment by ilgrosso** [comment]
FYI I've opened #200 to fix OSS Sonatype deployment

**Comment by ilgrosso** [comment]
Now that Wicket 10.0.0-M1 is out, any chance to cut a relase from the `wicket-10` branch here?

**Comment by MarcGiffing** [comment]
There is no milestone release for Wicket Stuff....

<wicketstuff.version>10.0.0-SNAPSHOT</wicketstuff.version>

**Comment by ilgrosso** [comment]
@MarcGiffing wise question: https://github.com/wicketstuff/core/issues/752

**Comment by ilgrosso** [comment]
@MarcGiffing we have now both WicketStuff 10.0.0-M1 and Wicket-Bootstrap 7.0.0 released:

* https://github.com/wicketstuff/core/releases/tag/wicketstuff-core-10.0.0-M1
* https://github.com/l0rdn1kk0n/wicket-bootstrap/releases/tag/bootstrap-parent-7.0.0

**Comment by MarcGiffing** [comment]
👍
