### ISSUE TITLE
Autoconfigure for Wicket Atmosphere

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#2]
https://github.com/apache/wicket/tree/master/wicket-experimental/wicket-atmosphere

**Comment by MarcGiffing** [comment]
It seems that the atmosphere.xml is not found. The atmosphere-runtime-xx.jar uses

AtmosphereFramework.java line 2100
``` java 
logger.info("Auto detecting atmosphere handlers {}", handlersPath);

String realPath = servletContext.getRealPath(handlersPath);
```

The getRealPath method of the ServletContext is pointed to a wrong directory:
http://stackoverflow.com/questions/26849636/embedded-tomcat-executable-jar-servletcontext-getrealpath

Further investigation needed...

**Comment by ceefour** [comment]
so this is Spring Boot's fault?

**Comment by MarcGiffing** [comment]
If I remember correctly the problem was that the atmohsphere.xml could not been detected in an executable jar. The problem is located in the AtmosphereFramwork class of the atmosphere project itself.

You've also the possibility to thet the information of the atmophere.xml directly in the code but I've also have there some problems. 

I'll try it again and post the status here. I'm a little bit busy but i try to take a look next week...
