### ISSUE TITLE
Spring Boot Dev Tools Error

### ISSUE THREAD

**Issue by brielmayer** [MarcGiffing/wicket-spring-boot#203]
We successfully updated our Apache Wicket application using the wicket-spring-boot project to integrate with Spring Boot:
```
@Component
public class Application extends com.giffing.wicket.spring.boot.starter.app.WicketBootSecuredWebApplication {
...
}
```

The application is running well, but when we add `org.springframework.boot:spring-boot-devtools` as a dependency, we encounter an error:
```
Description:

Field generalSettingsProperties in com.giffing.wicket.spring.boot.starter.app.WicketBootSecuredWebApplication required a bean of type 'com.giffing.wicket.spring.boot.starter.configuration.extensions.core.settings.general.GeneralSettingsProperties' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:
Consider defining a bean of type 'com.giffing.wicket.spring.boot.starter.configuration.extensions.core.settings.general.GeneralSettingsProperties' in your configuration.
```

Additional info:
Spring Version: 2.7.13
Wicket Version: 9.14.0
Wicket Spring Boot Version: 3.1.7

Do you have any suggestions to fix this issue?

**Comment by MarcGiffing** [comment]
Is the Spring Boot Security Starter present?
Can you remove the "extends com.giffing.wicket.spring.boot.starter.app.WicketBootSecuredWebApplication" part? 
Have you tried the Example Project?
