### ISSUE TITLE
AnnotatedMountScanner did not create pretty URLs

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#23]
The annoated mount scanner is called the pages annotated with @MountPath are detected. But the page links still including the full qualified class name. If you mount the pages directly it works.

I've created two pages FirstPage and SecondPage. On is mounted in the init method of the WicketApplication and the other is configures via the annotated mount scanner. Only the explicitly mounted page is working.

**Comment by MarcGiffing** [comment]
The cause of the problem is Spring Boots dev tool dependency. If its present the mountin is broken.

**Comment by MarcGiffing** [comment]
The problem is that spring boot devtools is reloading classes from the class path so the relaoding classes gets a new id. In the class MountedMapper is a comparison of two classes with equals which will fail everytime cause of the class reloading. 

```
@Override
protected boolean checkPageClass(Class<? extends IRequestablePage> pageClass)
{
	return pageClass.equals(this.getPageClass());
}
```

You can fix the problem by adding a property "META-INF/spring-devtools.properties" which tells spring boot devtools to also reaload the wicketstuff-annotation.jar.

**Comment by martin-g** [comment]
> You can fix the problem by adding a property "META-INF/spring-devtools.properties" which tells spring boot devtools to also reaload the wicketstuff-annotation.jar.

What is the name=value of this property?

**Comment by martin-g** [comment]
Oh, I see it at https://github.com/MarcGiffing/wicket-spring-boot/commit/0e5d9672d95d86b97b56c747209e894634db7b26
Sorry, I didn't see the commit before that.
