### ISSUE TITLE
Optimize slow Tests - Reuse WicketTester for all tests and remove @DirtiesContext

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#31]

**Comment by MarcGiffing** [comment]
If the WicketBootWebApplication is reused in the tests the WicketTester throws an exception that the application name can only be used once. With @DirtiesContext we told wicket that springs application context should be build up for each test. This is time consuming.
``` java 
java.lang.IllegalStateException: Application name can only be set once.
	at org.apache.wicket.Application.setName(Application.java:991)
```

The current alternative is to reuse the WicketTester for all tests and don't create a new one for eacht test. This may affect tests among each other but it seems the only short-term solution.

Ideas or contributions are welcome...

**Comment by martin-g** [comment]
The pasted stacktrace is too short to guess what could be improved.
Please create a ticket at Apache JIRA with more details and we will see how to make it better.
Recently we did this improvement: https://github.com/apache/wicket/commit/792a0a4138aad61dfe63c8bace96648878767003
It should be something similar for WicketTester too.
Thanks!

**Comment by MarcGiffing** [comment]
I've created a ticket. I will also think about a better Spring configuration solution
https://issues.apache.org/jira/browse/WICKET-6053

**Comment by martin-g** [comment]
Thanks!

**Comment by MarcGiffing** [comment]
Okay, the static WicketTester solution is not an option. If multiple tests are executed the tests execution failed. Back to @DirtiesContext.

**Comment by tdziurko** [comment]
So what is current approach to test Wicket Pages and Panels when using wicket-spring-boot library? Extending WicketBaseIntTest with DirtiesContext annotation? I am asking as it worries me a bit that I am unable (or find it hard now) to write reasonable tests for non trivial Pages using some Spring Beans etc.

**Comment by tdziurko** [comment]
Ok, I have tried some different approaches to overcome this problem and ended up with small hack that prevents Application from starting up for each test.

In Spock I have something like this in my setup() method:

    def setup() {
        ReflectionTestUtils.setField(wicketApplication, "name", null)
        tester = new WicketTester(wicketApplication)
    }

as it looked to me that only this name setting logic is causing troubles during WicketTester instantiation. Full test spec can be viewed here: https://github.com/tdziurko/jvm-bloggers/blob/f5932f2e5c1055400a5223d89bfe13deefedbfdd/src/test/groovy/pl/tomaszdziurko/jvm_bloggers/view/login/LoginPageSpec.groovy

**Comment by MarcGiffing** [comment]
I don't know if there are side affects on reusing the WebApplication for all tests. I've also created a solution where you create a new instance of the WebApplication and set the beans via the ReflectionTestUtils.

**Comment by Shadowrunner** [comment]
My solution is the following:

`	
       private static WicketTester tester;

       @Before
	public void setup() {
		String absolutPath = TestUtil.getAbsolutContextPath();
		if(tester == null){
			tester = new WicketTester(myWebApplication, absolutPath);
	        }
         }

	@AfterClass
	public static void destroy(){
		tester.destroy();
		tester = null;
	}
`

This way, WicketTester is instantiated once per testclass and destroyed after all testmethods are done.

**Comment by martin-g** [comment]
https://issues.apache.org/jira/browse/WICKET-6053 has been fixed.
Please try with 7.3.0-SNAPSHOT if you are able,

For me building master fails with:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project wicket-spring-boot-starter: Compilation failure: Compilation failure:
[ERROR] /home/martin/git/wicket-spring-boot/wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/configuration/extensions/stuff/datastore/memcached/DataStoreMemcachedConfig.java:[22,25] package net.spy.memcached does not exist
[ERROR] /home/martin/git/wicket-spring-boot/wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/configuration/extensions/stuff/datastore/redis/DataStoreRedisConfig.java:[21,27] package redis.clients.jedis does not exist
[ERROR] /home/martin/git/wicket-spring-boot/wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/configuration/extensions/stuff/datastore/memcached/DataStoreMemcachedConfig.java:[41,21] cannot find symbol
[ERROR] symbol: class MemcachedClient
[ERROR] /home/martin/git/wicket-spring-boot/wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/configuration/extensions/stuff/datastore/redis/DataStoreRedisConfig.java:[39,21] cannot find symbol
[ERROR] symbol: class Jedis
[ERROR] -> [Help 1]
```

**Comment by MarcGiffing** [comment]
My PC is broken. I'll take a look if its fixed.

**Comment by MarcGiffing** [comment]
I don't get the compiler errors above. I'm using a fresh new notebook...
I've updated to 7.3.0 and removed the DirtiesContext annotations. The error with the application name is gone but now I got side effects on tests which submits the same form. I have to investigate it a little bit more...

**Comment by MarcGiffing** [comment]
Spring Boot 1.4.0 introduced some new annotions like @SpringBootTest or MockBean. The tests should be updated. 

The configuration must be improved. Maybe some predefined classes in the starter project from which the tests could inherit. Or some special annotation which configures the test automatically...
