### ISSUE TITLE
Executable Jar - Wicket WebJars - current version is not detected

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#35]
If the jar file of the example project is launched the webjars resources are not detected.

In the BasePage the bootstrap.js and the bootstrap.css are configured with the string 'current' which should be replaced by the current existing version.

``` java 
response.render(JavaScriptHeaderItem.forReference(new WebjarsJavaScriptResourceReference("bootstrap/current/js/bootstrap.js")));
		response.render(CssHeaderItem.forReference(new WebjarsJavaScriptResourceReference("bootstrap/current/css/bootstrap.css")));
/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/bootstrap/null/js/bootstrap.js
``` 

If the application is launched in eclipse the version is correctly replaced.
``` 
./wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/bootstrap/3.3.6/js/bootstrap-ver-1449931369771.js
``` 

If the jar file is launched directly we get a null string instead of the version in the url.
``` 
/wicket/resource/de.agilecoders.wicket.webjars.request.resource.WebjarsJavaScriptResourceReference/webjars/bootstrap/null/js/bootstrap.js
```

**Comment by martin-g** [comment]
It is not your fault! :-)
https://github.com/l0rdn1kk0n/wicket-webjars/issues/37

**Comment by MarcGiffing** [comment]
Ah, thanks for your response!

**Comment by martin-g** [comment]
See the discussion at wicket-bootstrap linked in the description. 
The problem is that now the start of Spring-Boot apps is 10+ secs slower.
That's why this commit is not yet released.

I wanted to check whether migrating to webjar-selector will fix this issue, but I didn't have time to experiment so far.

**Comment by MarcGiffing** [comment]
What is webjar-selector? I couldn't find anything about it. 

Maybe a property configuration would be helpful where you can define the jar files which should be scanned. On startup an error should be thrown if the resource is not found. The configuration/property file can also be generated on compile time...

**Comment by martin-g** [comment]
Sorry, I meant `webjars-locator` (http://search.maven.org/#search|ga|1|webjars-locator).
There is some documentation at http://www.webjars.org/documentation > Spring MVC.

The problem in wicket-webjars comes from the support for `current` as a replacement of the actual version. This is the reason for the scanning at all.

**Comment by MarcGiffing** [comment]
OK, the next problem is the current placeholder. Its not working in an embedded JAR cause the JarAssetPathCollector creates a File object to access the webjars JAR files. The problem is that you have a jar which includes a jar.

The code:
`final File file = new File(URI.create(path.substring(0, path.indexOf("!"))));`
does not retrieves the path to the webjar. 

`jar:file:/C:/path/project/target/project.jar!/lib/bootstrap-3.3.6.jar!/META-INF/resources/webjars`

Instread you'll get

`/lib/bootstrap-3.3.6.jar!/META-INF/resources/webjars`

I've tried to use lastIndexOf("!") but then you'll get an error cause you can't create a file object of an embeded jar:

`C:\path\project\target\project.jar!\lib\bootstrap-3.3.6.jar`

I don't know if there is an easy way to solve this problem. Any ideas?

**Comment by MarcGiffing** [comment]
Couldn't the classloader used to retrieves the file information? We don't have to check if its a jar file or not. Only the '/META-INF/resources/webjars' folder should be filtered. I'll create a ticket in the webjars project.
