### ISSUE TITLE
Redundant Dependencies

### ISSUE THREAD

**Issue by lazaridis-com** [MarcGiffing/wicket-spring-boot#43]
The starter-pom contains some wicket dependencies (without use of `${wicket.version}`):

https://github.com/MarcGiffing/wicket-spring-boot/blob/master/wicket-spring-boot-starter/pom.xml#L42

but those are already within the parent-pom (with use of `${wicket.version}`):

https://github.com/MarcGiffing/wicket-spring-boot/blob/master/pom.xml#L72

Not sure here, but It seems that the root-pom should be kept minimal, thus one can verify the dependencies of the starter-pom by looking only within one file.

**Comment by MarcGiffing** [comment]
The dependencies in the parent project are defined in the depndency management section. I've used this to define a default configuration for all sub maven-modules. If you look at the wicket-spring-boot-context module you will see the wicket-core dependency without a version. The version is inherited from the parent pom. The same wicket-core dependency is used in the wicket-spring-boot-starter pom.

With this structure you only have to change the version in the parent pom for all sub modules.

**Comment by lazaridis-com** [comment]
My fault, I've totally overlooked the `<dependencyManagement>` tag.
