### ISSUE TITLE
Wicketstuff into own starter?

### ISSUE THREAD

**Issue by lazaridis-com** [MarcGiffing/wicket-spring-boot#45]
I'm starting a project based on spring-boot, most possibly in combination with wicket, and thus I hit on this project here (due to the typical laziness to do all the work myself).

The starter-pom contains many dependencies, some of them seem to not belong to wicket itself (wicketstuff). I'm new to wicket, so I don't know if e.g. this `wicketstuff` is optional or if a typical wicket-application cannot be build without wicketstuff.

Wouldn't it be preferable to have a separate starter for the wicketstuff, thus a user (e.g. me) is not forced to include the wicketstuff into his project when using the wicket-starter?

**Comment by MarcGiffing** [comment]
The wicketstuff dependencies have the scope provided:
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html

provided
This is much like compile, but indicates you expect the JDK or a container to provide the dependency at runtime. For example, when building a web application for the Java Enterprise Edition, you would set the dependency on the Servlet API and related Java EE APIs to scope provided because the web container provides those classes. This scope is only available on the compilation and test classpath, and is not transitive.

So the dependencies are optional and will added to you project.

**Comment by lazaridis-com** [comment]
I am aware of the `provided` mechanism.

Why is the wicketstuff mentioned at all, even if it's just `provided`? I understand that it is **optional** stuff, so it should not be mentioned at all within the wicket-starter pom.

**Comment by MarcGiffing** [comment]
Without the dependencies I could not add autoconfigurations for the specific extensions.

The configuration of the [AnnotatedMountScannerConfig](https://github.com/MarcGiffing/wicket-spring-boot/blob/master/wicket-spring-boot-starter/src/main/java/com/giffing/wicket/spring/boot/starter/configuration/extensions/stuff/annotationscan/AnnotatedMountScannerConfig.java) checks if a specific class in in the classpath:

`@ConditionalOnClass(value = org.wicketstuff.annotation.scan.AnnotatedMountScanner.class)`

Without the dependency there are compile time errors. Thats the reason why there are needed. We could move the wicketstuff dependencies to another project but we will not gain a benefit from that.

The user of this project will not notice the provided dependnecies.

**Comment by lazaridis-com** [comment]
Ok, I think I understand.

The main thing is: wicketstuff is **not** wicket, and thus a wicket-starter should **not** deal with wicketstuff extensions.

A separate `wicketstuff-spring-boot-starter` should autoconfigure wicket-stuff.

I understand that this is possibly no priority of yours (or even no elegant solution at all). But at least the current documentation should state that the wicket-starter deals additionally with wicketstuff (if found), thus there are no surprises for users.

**Comment by MarcGiffing** [comment]
But the wicketstuff-spring-boot-starter will not work without the wicket-spring-boot-starter. So the user has to add both dependencies. The wicket-spring-boot-starter has also auto configuration support for other projects which is not in the wicket core or wicket-stuff. Then we have to add another project for webjars, beanvalidation, wicket-source....

With this configuration the user needs only one dependency. Maybe I'm wrong so I'll let the issue open to hear the opinion of other users. And I'll try to provide a better documentation.

Thanks for your feedback!

**Comment by lazaridis-com** [comment]
(Ok, I can help with the docs, as I'm totally new to all this stuff).

As for the splitting decision, some comments:

> But the wicketstuff-spring-boot-starter will not work without the wicket-spring-boot-starter.

This would be natural

> The wicket-spring-boot-starter has also auto configuration support for other projects which is not in the wicket core or wicket-stuff.

This is the typical processing of spring-starters: configure typical use-cases, e.g.:

* if project A is found, configure it
* if project B is found, configure it
* if combination of project A & B is found, configure it

> Then we have to add another project for webjars, beanvalidation, wicket-source....

No, that would be something like `over-modularization`. 

As a basic rule, commonly used functionality should be processed from the main starter (here: wicket-starter).

So possibly I now have just stated a rule, which makes inclusion of wicketstuff-config within the wicket-starter valid (because for a wicket app, wicketstuff **is** commonly used functionality).

But: if the functionality introduced by wicketstuff is very large (another criterion), then splitting-out in an own starter should be the right thing to do.

(REVISIT 201603)
