### ISSUE TITLE
Configuration support without Spring Security

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#5]

**Comment by Centonni** [comment]
Hi @MarcGiffing , thank you for this nice toolkit!
I am using wicket-spring-boot for a hobby project and i face the spring security default configuration issue, i am using apache shiro for security related things. 
I could work on this, but i have to know what is the best thing to do : 
-remove all dependency to spring-security and let clients add it if they want
-provide a mechanism to disable/enable spring security via properties or annotation
Let me know what you think is the best or if you are already working on it!

**Comment by MarcGiffing** [comment]
For this ticket I wan't to create two WebApplication classes one default without Spring Security and one with Spring Security. The Spring Security part should be moved to the extensions section. So Apache Shiro should also be placed in the extension section. My idea is to create an abstract AuthenticatedWebApplication class which can be extend by Apache Shiro and Spring Security.

The Spring Security dependencies should be scoped as provided. If you can wait I will move the Spring Security part to the extension section to give you a 'template'.

Maybe you have a better idea...pull requests are welcome :)

https://github.com/MarcGiffing/wicket-spring-boot/issues/41

**Comment by Centonni** [comment]
Definitely the best solution so far!
I therefore expect your changes to see how I can manage with apache shiro, thanks!

**Comment by MarcGiffing** [comment]
@Centonni. OK I moved the Spring Security configuration to com.giffing.wicket.spring.boot.starter.configuration.extensions.external.spring.security. Look at the class AuthenticatedWebSessionConfig. Here you can define a bean of AuthenticatedWebSessionConfig which holds the security configuration. At the moment you only have to implement the method which returns a class of type AbstractAuthenticatedWebSession.

Maybe it's not the final solution...what do you think?
