### ISSUE TITLE
Simplify / Normalize Application Initialization

### ISSUE THREAD

**Issue by lazaridis-com** [MarcGiffing/wicket-spring-boot#51]
From https://github.com/lazaridis-com/spring-entry/issues/1#issuecomment-179190457

> The main application code/class does not look like a typical spring-boot application. The code looks wicket-centric. Removing thymeleaf would be very simple, but removing wicket would result in neccessary code-changes.

> I'm not sure if it is achievable, but would it be possible to be a little bit less intrusive? Just adding a starter, and possibly some additional code for wicket, whilst keeping the basic main application code of a typical spring-boot application?

Is this possible? I remember to have seen something which adds wicket as some kind of `Filter` (please note that I do not retrieve at this point detail-knowledge. Just seeing it from the eyes of a typical simple user).

**Optimal**

* wicket-spring-boot-starter does not require any code at all (all is configured behind the scenes)
* the developer uses some defaults (e.g. homepage, loginpage etc.).

**very fine**

* wicket-spring-boot-starter requires **one** class, which adds itself to spring, without the need to change the main spring-boot application code.

**fine**

* wicket-spring-boot-starter requires **one** class, which is added by the developer to the main spring-boot application code.

**Comment by MarcGiffing** [comment]
In the early release I've provided a default loginpage and homepage. 

@martin-g mentioned that it makes no sense to provide those.
https://github.com/MarcGiffing/wicket-spring-boot/pull/30#issuecomment-166021901

And the WebApplication is the central class to configure a Wicket application. I don't think that it makes sense to hide it from the user.

Cause the homepage and loginpage are required none of these options are realizable. I'm totally with you cause I had the same idea.

**Comment by lazaridis-com** [comment]
default home/login is fine, but **only** if optional. So I agree that it's too much.

> And the WebApplication is the central class to configure a Wicket application. I don't think that it makes sense to hide it from the user.

It does make sense to hide it. Configure it and provide it. And if a user defines an own, then the autoconfiguration does not provide one. Just like spring-boot starters work.

-

So, you should distinguish:

* **wicket-spring-boot-starter** does the minimal neccessary work to get wicket running.
* **examples** provide a showcase of how to use it
* **wicket-super-duper-module** does more stuff, like basic login pages (this is **separate** functionality)

-

The main thing for the issue here is that the wicket-starter should not change the very basic SpringBootApplication main. Necessary imports would affect `wicket` and not `wicket-spring-boot-starter` contained classes or annotation.

```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

	public static void main(String[] args) {
		SpringApplication.run(App.class, args);
	}
}
```
