### ISSUE TITLE
0.0.9 doesn't work with Wicket 7.2.0

### ISSUE THREAD

**Issue by teeschke** [MarcGiffing/wicket-spring-boot#58]
Start up exit with code 0 after logged line
org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.30
=> just before Initializing Spring embedded WebApplicationContext

A downgrade to wicket-spring-boot 0.0.8 and implementing of getSignInPageClass fixed my issue.

It would be more than great if your "Getting started" guide would be aligned to the "Wicket Quickstart" at
https://wicket.apache.org/start/quickstart.html

**Comment by MarcGiffing** [comment]
I think this is due to the missing spring-boot-starter-web dependency. As I moved spring security starter to the extensions, the spring-boot-starter-web was also removed and produces this problem.

Please look at:
I'm not sure if this dependency should be added by default in the starter dependency

> https://github.com/MarcGiffing/wicket-spring-boot-examples
> https://github.com/MarcGiffing/wicket-spring-boot-examples/tree/master/simple

**Comment by MarcGiffing** [comment]
https://github.com/MarcGiffing/wicket-spring-boot/issues/63
