### ISSUE TITLE
Howto reload changed HTML without application restart?

### ISSUE THREAD

**Issue by tgoetz** [MarcGiffing/wicket-spring-boot#65]
Hi,

I'm currently playing around with your wicket-spring-boot integration, and I think I like it ;-)
One thing bothers me though: how can I change some HTML and get it reloaded without having to restart the application? This usually works out of the box e.g. when using the Jetty plugin. Any idea or even an example?

   Tom

**Comment by MarcGiffing** [comment]
Did you run the application in DEVELOPMENT mode? 
You can override the configuration with the following property:
wicket.core.settings.general.runtime-configuration=development # development/deployment(default)

You can also add the Spring Boot Devtools dependency to have a faster restart on code changes.
https://github.com/MarcGiffing/wicket-spring-boot#extension-springboot-devtools

**Comment by tgoetz** [comment]
Argh! Forgot to set 'development' runtime config, thanks for the hint!
