### ISSUE TITLE
Autoconfiguration - Wicket Metrics (7.3.0)

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#70]
https://github.com/apache/wicket/pull/164

**Comment by martin-g** [comment]
This will be interesting task! :-)
I want to see what could be auto-configured here!
Some hints:
- you need to add a javaagent
- you need to add aop.xml with the selected aspects

Have fun! :-)

**Comment by MarcGiffing** [comment]
Oh I didn't see that coming ;) But I could use Spring AOP as a default (slower more overhead) and switch to aspectj if present. Maybe something like that. I'll give it a try... and afterwards you can see me fail :)

**Comment by martin-g** [comment]
I don't have direct experience with Spring AOP. I have used it only transitively. I'll be glad to learn something new!

Good luck!

**Comment by klopfdreh** [comment]
As of this post: http://stackoverflow.com/questions/9666922/enable-spring-aop-or-aspectj - Spring supports the AspectJ annotation.

@MarcGiffing have you tried this code snippet:
```xml
<aop:aspectj-autoproxy />
<context:component-scan base-package="org.apache.wicket.metrics.aspects, org.yourpackage" />
```

If this works you don't need to have an aop.xml anymore. However the agent is still required I guess.

**Comment by MarcGiffing** [comment]
Sorry for the delay. Yes Spring supports Aspectj annotations. But the target classes should be Spring beans. The current support for the Aspects under org.apache.wicket.metris.aspects are working with the agent. I'm currently only support some configuration options for the Graphite and Console reporter.

Currently I put the aop.xml in the starter project but now you couldn't modify the aspect classes. I could remove the aop.xml and configure each class as a Spring bean. WIth this configuration I could enable/disable each bean via properties (if its possible).

**Comment by klopfdreh** [comment]
The only thing which has to be ensured is that WicketFilterInitAspect is loaded before the Wicket application is initialized.

The other option is if you use xml for the bean definition - declare every aspect as bean / you have to take the pointcuts out of the aspect classes. Or you use component scanning to load the aspects (as described in my post before)

The names of the aspect tell what they are doing - you have to enable only the required.

Example:

ComponentOnRenderAspect - creates for each component a metric that shows how long it took to render it.

**Comment by klopfdreh** [comment]
Just one addition. Every Aspect is used for a different metric - you can see the behavior within the aspect itself. In the example of the ComponentOnRenderAspect:

@Around("execution(* org.apache.wicket.Component.onRender(..))")

And the metric is listed within Graphite under the application name with:

measureTime("core/component/render", joinPoint);

So:

&lt;application_name&gt;/core/component/render/&lt;package&gt;/&lt;component_name&gt;

**Comment by MarcGiffing** [comment]
> The other option is if you use xml for the bean definition - declare every aspect as bean / you have to take the pointcuts out of the aspect classes. Or you use component scanning to load the aspects (as described in my post before)

I'm using Java class configuration instead of XML configuration. But the beans are not detected without the aop.xml. I also tried spring-instrument but without luck.

The component scanning alone won't work cause if using Spring the classes have to be Spring beans (I think it is so). 

I don't give up...

**Comment by klopfdreh** [comment]
Hi @MarcGiffing ,

if you use component scanning within packages try to add:

```java
context.register(AnnotationAwareAspectJAutoProxyCreator.class);
```

See the documentation about it here: http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/aop/aspectj/annotation/AnnotationAwareAspectJAutoProxyCreator.html

**Comment by MarcGiffing** [comment]
Then I've no control which aspect should be enabled and which not or am I wrong?

I will add an exporter for https://github.com/prometheus/prometheus cause I havn't a running instance of Graphite. Maybe its also interessting to you. I've read somewhere it supports the Graphite interface.
