### ISSUE TITLE
Upgrage to Wicket 7.4.0

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#73]

**Comment by MarcGiffing** [comment]
The tests are failing now: 
> java.lang.AssertionError: path: 'form:passwordBorder:passwordBorder_body:password' does not exist for page: CustomerEditPage

The CustomerEditPage extends CustomerCreatePage. The tests in the CustomerCreatePageTest are working.

@martin-g are there any changes in the path resolution? I couldn't find anything in the change logs.

**Comment by martin-g** [comment]
There were two regressions related to borders + queued components.
Please try with 7.5.0-SNAPSHOT and create a ticket if it still fails.
Thank you!

**Comment by MarcGiffing** [comment]
I still got the error with 7.5.0-SNAPSHOT. I will create a jira ticket

> Implementation-Title: Wicket Core
Built-By: buildslave18
Tool: Bnd-2.3.0.201405100607
Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.7))"
Implementation-Vendor: Apache Software Foundation
Implementation-Vendor-Id: org.apache.wicket
Specification-Title: Wicket Core
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-SymbolicName: org.apache.wicket.core
Implementation-Version: 7.5.0-SNAPSHOT
Specification-Vendor: Apache Software Foundation
Bundle-Name: Wicket Core
Created-By: Apache Maven Bundle Plugin
DynamicImport-Package: *
Bundle-Vendor: Apache Software Foundation
Build-Jdk: 1.7.0_75
Bundle-Version: 7.5.0.SNAPSHOT
Bnd-LastModified: 1469632561544
Bundle-ManifestVersion: 2

**Comment by martin-g** [comment]
Sorry about that!
Next time I'll use the examples to test the Wicket release!

**Comment by MarcGiffing** [comment]
You do not have to apologize! I'm thankful that you react to my requests! :+1:
