### ISSUE TITLE
Scanner not finding all Pages

### ISSUE THREAD

**Issue by thomasveit** [MarcGiffing/wicket-spring-boot#75]
Hi there, 
I'm working on a own framework. In a base artifact for the web frontend I'm calling the AnnotatedMountScanner. This artifact is uploaded to a nexus server and the frontend project includes this jar. 

So now my problem:

If I include this artifact over nexus, then it only finds my pages inside of jar file. But the compiled classes in the frontend project aren't available at the specified mount url. Can you tell me what reason it can be that this is happening? I have also debugged through it. The scanner is finding my pages but when it comes to the part where wicket is processing the mount strategies, there the compiled classes suddenly aren't in the list anymore.

I hope someone can help me. 

Kind regards 
Thomas

**Comment by MarcGiffing** [comment]
Can you give more details about your project configuration? DId you use the wicket spring boot starter at all? Can you provide some code snippets? Hwo do you call the Wicket part of your external jar?

**Comment by thomasveit** [comment]
Jar Files in Nexus:
- framework-ui.jar
- framework-user-ui.jar

My project includes both of them.

framework-ui.jar has a FrameworkApplication Class which is started in the Project.
Also the MyWicketApplication class is in my framework-ui.jar file. It is thought that you have to create a minimalistic set of files to start a new project.

So all pages in the framework-ui.jar and framework-user-ui.jar are found and processed correctly, but the pages in the specific project not. 
If I change the dependencies from jar files to project dependencies it works. 
As workaround now I have created an additional WicketApplicationInitConfiguration in the project and there I call the Scanner again with

`
new AnnotatedMountScanner().scanPackage("myframeworkpackage").mount(webApplication);
`

This was the only solution until now that it is working correctly. If I use the build in AnnotatedMountScannerConfig it doesn't find any Page in all projects. So I changed everything to the WicketApplicationInitConfiguration.

Gradle for framework-ui.jar project:

`
ext {
	wicketVersion = "7.3.0"
}


dependencies {
	// Starter Dependencies
	compile "org.springframework.boot:spring-boot-starter" 
	compile "org.springframework.boot:spring-boot-starter-web" 
	compile "org.springframework.boot:spring-boot-starter-security" 
	compile "org.springframework.boot:spring-boot-starter-mail"
	compile "org.springframework.boot:spring-boot-configuration-processor" 
        compile "org.springframework.boot:spring-boot-starter-thymeleaf"

	// Weitere Dependencies	
	compile "org.reflections:reflections:0.9.10" 
	compile "org.apache.commons:commons-lang3:3.4" 
	compile "org.apache.httpcomponents:httpclient:4.5.2" 
	
	// Wicket Dependencies
	compile "com.giffing.wicket.spring.boot.starter:wicket-spring-boot-starter:0.0.+" 
	compile "org.apache.wicket:wicket:${wicketVersion}" 
	compile "org.apache.wicket:wicket-bean-validation:${wicketVersion}" 
	compile "org.apache.wicket:wicket-devutils:${wicketVersion}"
	compile "org.wicketstuff:wicketstuff-annotation:${wicketVersion}" 
}	
`

Gradle for my project using this framework:

`
dependencies {
	compile "my.framework:framework-ui:0.1.+"
	compile "org.springframework.boot:spring-boot-devtools"
	runtime "my.framework:frameowrk-user-ui:0.1.+"
}
`

**Comment by thomasveit** [comment]
Just found another strange behaviour:

If I call a page which is annotated with @MountPath in my project then the Injection of @SpringBean doesn't work anymore. It cannot find Beans in the ApplicationContext. If I remove the MountPath Annotation then it works again.

**Comment by MarcGiffing** [comment]
Can you check that you are using the latest version 0.0.15?

The AnnotatedMountScannerConfig should scan all packages which are scanned by spring. Did you add Springs component scan on all packages your are using? Can you debug the AnnotatedMountScannerConfig and look at candidates.getBasePackages() to see if your package is included? 

It's strange that the packaged jar version has a different behaviour. Did you use Spring Devtools? It is possible that there are some problems with the reload mechanism and Wicket.

Can you provide the code of the MyWicketApplication class? Is it a simple one like
[Wicket annotationscan example](https://github.com/MarcGiffing/wicket-spring-boot-examples/blob/master/annotationscan/src/main/java/com/giffing/examples/wicket/spring/boot/annotationscan/WicketApplication.java) ? 
Did you extend from another class?

**Comment by thomasveit** [comment]
The AnnotatedMountScanner is finding all the pages. But when it goes to the Mounting in Wicket they disappeared in the List of Pages which have to be mounted.

**Comment by thomasveit** [comment]
Hi, I removed Spring Dev Tools from classpath and everything was find. Thank you for your Help :)

**Comment by MarcGiffing** [comment]
Only a hint also for other people facing the same problem. If you want to use Spring Boot Devtools with an external Jar you may have to add the jar to the [spring-devtools.properties](https://github.com/MarcGiffing/wicket-spring-boot/blob/master/wicket-spring-boot-starter/src/main/resources/META-INF/spring-devtools.properties). It tells Spring Boot Devtools to add the Jar "classes" to the restart classloader.
