### ISSUE TITLE
wicket-source -  42Lines to jennybrown8 (?)

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#78]
https://github.com/jennybrown8/wicket-source/wiki

**Comment by MarcGiffing** [comment]
There is no new release at the moment.

**Comment by jennybrown8** [comment]
There is now a release of wicket-source for Wicket 8.  It's under a new name:
com.github.jennybrown8.wicket-source
version 8.0.0

**Comment by MarcGiffing** [comment]
Thank you!
