### ISSUE TITLE
Autoconfiguration Datastore Redis kicks in while it should not.

### ISSUE THREAD

**Issue by drzewo** [MarcGiffing/wicket-spring-boot#81]
I suggest that DataStoreRedisConfig should be annotated with @ConditionalOnClass specifying some other class (contributed by wicketstuff datastore redis project, be it org.wicketstuff.datastores.redis.IRedisSettings) rather than Jedis, as it results 
java.lang.NoClassDefFoundError: org/wicketstuff/datastores/redis/IRedisSettings at startup when your project makes use of Jedis but not Redis Datastore.

**Comment by MarcGiffing** [comment]
You're right! I've added the RedisDataStore to @ConditionalOnClass.  Until the next release you could disable  the Wicket Redis support with the property wicket.stuff.datastore.redis.enabled.
