### ISSUE TITLE
Wicket tags in output

### ISSUE THREAD

**Issue by philippn** [MarcGiffing/wicket-spring-boot#84]
Hello Marc,
first of all sorry, if this is wrong here. I'm not sure if this is a problem in my setup, in wicket itself or the Spring Boot integration, Anyway here it is: I haven't set any properties, so the application is running in DEPLOYMENT mode. Still, I can see the wicket tags in the output.

Explicitly calling MarkupSettings.html#setStripWicketTags(true) does not seem to have any effect either.

Do you havee any idea what's going on? Thanks in advance!

**Comment by MarcGiffing** [comment]
The normal configuration without the starter projects is in Wickets org.apache.wicket.Application#configure() method which is called before the com.giffing.wicket.spring.boot.starter.configuration.extensions.core.settings.markup.MarkupSettingsConfig is called. The MarkupSettingsConfig uses the development configuration which is the default one in org.apache.wicket.settings.MarkupSettings.

As a workaround you have to override the property to change the behaviour.

The default configuration should be the deployment configuration. I will check all configurations and list them here to clarify the changes which must be taken.

Maybe the development configuration should be enabled if the Spring Boot Devtools project is present/active and change specific configurations. 

What do you think?

**Comment by philippn** [comment]
Personally I don't use the Spring Boot devtools. Making the deployment mode the default (including strip tags set to true and the other default markup settings) sounds reasonable. I would expect that it is then possible to disable the tag stripping by setting the property to false explicitly? And the same goes for the other markup related settings? It would probably be a good idea to document the defaults somewhere and how to override them if needed.

Thanks alot for your efforts! :-)

**Comment by philippn** [comment]
I have upgraded to 1.0.1 and the wicket tags are gone now by default. I'm happy and this issue can be closed. Thanks alot for your time!
