### ISSUE TITLE
Wicket 8 Support

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#85]

**Comment by MarcGiffing** [comment]
@martin-g 
OK, the update to Wicket 8 was quite easy but my tests are failing now. After the log-in form is submited the response page is successfully set to the HomePage but in the test your still on the LoginPage

junit.framework.AssertionFailedError: classes not the same, expected 'class com.giffing.wicket.spring.boot.example.web.pages.home.HomePage', current 'class com.giffing.wicket.spring.boot.example.web.pages.login.LoginPage'

In the M3 I can't find any bug which is related to this problem. Should I open an Issue?

**Comment by martin-g** [comment]
Sure!
But please try to reproduce it in a simple quickstart. It might be a bug in your app/tests ;-)

**Comment by MarcGiffing** [comment]
https://github.com/MarcGiffing/wicket-spring-boot-examples/tree/master/spring-security
I'll create a ticket.

**Comment by martin-g** [comment]
Great!
I have some tasks to do these days but if noone else do it in the meantime I'll debug it in the coming days.

**Comment by MarcGiffing** [comment]
https://issues.apache.org/jira/browse/WICKET-6310

**Comment by eximius313** [comment]
@MarcGiffing,
since https://issues.apache.org/jira/browse/WICKET-6310 is already resolced - do you have plans to support Wicket 8 now?

**Comment by MarcGiffing** [comment]
I've already a working branch which should be updated with the master and then released. I'm not sure which version should be used...

**Comment by martin-g** [comment]
> I'm not sure which version should be used...

What do you mean with this ?

**Comment by MarcGiffing** [comment]
The current Wicket 7 master branch version is 1.x.x. Should the Wicket 8 branch be versioned with 2.x.x. Or should I versioned it depending on the wicket major releases 7.x.x and 8.x.x.?

**Comment by martin-g** [comment]
As you prefer.
For Wicket-Bootstrap I decided to use 2.x for the version compatible with Wicket 8.x.
Just add this info in the README so the users don't have to ask you again and again.

**Comment by MarcGiffing** [comment]
@eximius313 please try version 2.0.0. It uses Wicket 8.0.0.M4
