### ISSUE TITLE
spring boot 1.5 compatibility

### ISSUE THREAD

**Issue by osteinhauer** [MarcGiffing/wicket-spring-boot#88]
Hi.

As of spring boot 1.4 `org.springframework.boot.context.embedded.ServletContextInitializer` is deprecated. It is used (at least) in `com.giffing.wicket.spring.boot.starter.web.WicketWebInitializer`.

When upgrading to spring boot >= 1.5 applications won't start because of:

```
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [com.giffing.wicket.spring.boot.starter.WicketAutoConfiguration]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/boot/context/embedded/ServletContextInitializer.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:579)
```

Any plans? Or workarounds (besides copying the deprecated `ServletContextInitializer` in projects classpath 😉)?

**Comment by MarcGiffing** [comment]
My workaround is a new release! ;) Uploaded to the Maven central repository. Should be available soon. Have fun!
