### ISSUE TITLE
Can't login into application

### ISSUE THREAD

**Issue by JurassCZ** [MarcGiffing/wicket-spring-boot#89]
When I run wicket-spring-boot-example in IntelliJ, login page doesn't acquire credentials contained in test-data.xml, which I presume to use as login credentials:

login: frodo
#: 123

etc.

Actually, I'm not surprise with this kind of problem on Java platform: somebody run Spring example but can't log in. How typical, something is wrong... wish you good times with Java, I'm returning to .NET.

**Comment by MarcGiffing** [comment]
Oh, these users are not for the login. The class WicketWebSecurityApapterConfig is responsible for the security configuration and there is a hardcoded user admin with the password admin.

Maybe I shouldn't use customer entities as an example which also contains passwords...

So It's not Javas fault :)

**Comment by JurassCZ** [comment]
It's actually funny to have credentials hidden in one of many classes. But it's not your mistake, you are using Spring Security which have some automatized "wannabe simple" behavior. Normal security, used in .NET WCF for example, is working as programmer expect: You have to manually check if user in request have correct rights. Which is the most KISS as possible.

**Comment by MarcGiffing** [comment]
I don't what are you up to? You can implement any strategy that you wan't. I don't think that .NET is superior here. But thats not part of this proejct.

**Comment by JurassCZ** [comment]
Yes you can implement any strategy you want on this platform. So what strategy did you choose for credentials? It's the Catch Me If You Can strategy? :D Everybody can make mistake but on some platforms, some people can makes more mistakes just because they simply can. No offens and sorry for offtopic.
