### ISSUE TITLE
Add Apache Shiro support

### ISSUE THREAD

**Issue by mavortius** [MarcGiffing/wicket-spring-boot#92]
There is a [shiro-spring-boot-web-starter](https://mvnrepository.com/artifact/org.apache.shiro/shiro-spring-boot-web-starter) lib to integration with Spring Boot, but I don't know how I can use this to integrate with yours libs. I tried on different ways but without success. There is a project from [Wicketstuff](https://github.com/wicketstuff/core/tree/master/shiro-security), it could be a starting point to do that. I think Apache Shiro is a good project to implement security layers better than Spring Security.

**Comment by MarcGiffing** [comment]
I'll provide an example project and then we can discuss how the autoconfiguration can look like(if needed). A quick test works with the shiro web starter project.

**Comment by MarcGiffing** [comment]
Please try the following project: https://github.com/MarcGiffing/wicket-spring-boot-examples/tree/master/shiro-security

**Comment by mavortius** [comment]
The test with your provided example was ok, but when I tried to redirect to requested page with 'continueToOriginalDestination()', I got this 'org.apache.wicket.NonResettingRestartException' after a successful login and the application don't redirect to original requested page.. Maybe it was happen because I'm using 'Annotationscan' from Wickektstuff. In my test, for the HomePage class, I used '@MountPath("home")'.

**Comment by mavortius** [comment]
I did another test, this time removing the dependency of the 'Annotationscan' and the annotations and the error persists. The redirect action don't occurs.

**Comment by MarcGiffing** [comment]
I've updated the example. 

* Call /home
* Login with admin/admin
* You should be redirected to /home

The exception is thrown on purpose. But I think you shouldn't see it.

Javacod:

> Redirects to any intercept page previously specified by a call to redirectToInterceptPage.
 The redirect is done by throwing an exception. If there is no intercept page no exception
 will be thrown and the program flow will continue uninterrupted.

**Comment by mavortius** [comment]
Yes, by examining the code, I realized that this exception is always thrown. However, I noticed that the url is malformed. With the annotations, the url originally requested becomes "./home" (with a dot), and without the annotations, it becomes "./../ .." or something like that. This is very strange. I already use this integration of Wicketsuff-Shiro in a project with Java EE and the Annotationscan and the redirection normally occurs.

**Comment by martin-g** [comment]
With annotations your home page is mounted at `/home`.
Without annotations the path is something like `/wicket/bookmarkable/com.example.YourHomePage`.
So the relative path seems OK to me!

**Comment by mavortius** [comment]
Yes, that's right. The mistake was mine. I forgot to check, in the class constructor, if the user is already logged in.

**Comment by mavortius** [comment]
The next step is to read the settings from the application properties file, just as you did with "Spring Security".

**Comment by MarcGiffing** [comment]
Which settings. What exactly should be configured?

https://github.com/MarcGiffing/wicket-spring-boot-examples/blob/master/shiro-security/src/main/java/com/giffing/examples/wicket/spring/boot/shirosecurity/ShiroInitializer.java

```java
 public void init(WebApplication app) {
        AnnotationsShiroAuthorizationStrategy authz = new AnnotationsShiroAuthorizationStrategy();
        app.getSecuritySettings().setAuthorizationStrategy(authz);
        app.getSecuritySettings().setUnauthorizedComponentInstantiationListener(new ShiroUnauthorizedComponentListener(LoginPage.class, LoginPage.class, authz));
    }
```

I could provide a default AnnotationsShiroAuthorizationStrategy bean which can be overwritten.  I could also try to automatically set the login and unauthorized page.

But what about the other beans (TextConfigurationRealm, ShiroFilterChainDefinition)? Should we provide default beans? Maybe its better placed in the shiro starter project!?

What else should be auto configured?

**Comment by mavortius** [comment]
Normally there are some settings needed for the Shiro engine to work, such as the implementation of Realm (eg: JdbcRealm), dataSource, user query, role query, permission query, etc. Normally these settings are in a file called "shiro.ini" or a "web.xml" file, but in the case of "Spring Boot", it would be more appropriate if it could be configured through the application properties file.

**Comment by mavortius** [comment]
In your example, you have already included the dependency for "shiro-spring-boot-web-starter", so I believe that this starter should already have these properties configurable through the application properties file. Unfortunately, this starter (not the wicket starter) is poor in documentation. I'll check if there is anything similar in the source code.

**Comment by mavortius** [comment]
Examining the source code, I realized that there are only these configurable properties through the starter:

`shiro.loginUrl=
shiro.sessionManager.sessionIdCookieEnabled=
shiro.sessionManager.sessionIdUrlRewritingEnabled=
shiro.successUrl=
shiro.unauthorizedUrl=
shiro.web.enabled=`

So, the correct one would be to open an issue on the shiro starter and not here to add those customizations.

**Comment by mavortius** [comment]
I'm thinking some like:

`@ConfigurationProperties(prefix = ShiroProperties.PROPERTY_PREFIX)
public class ShiroProperties {
    public static final String PROPERTY_PREFIX = "wicket.external.shiro";

    private boolean enabled = true;

    private String userRolesQuery = "select role_name from user_roles where username = ?";

    private String authenticationQuery = "select password from users where username = ?";

    private boolean permissionsLookupEnabled = false;

    private String permissionsQuery = "select permission from roles_permissions where role_name = ?";

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(boolean enabled) {
        this.enabled = enabled;
    }

    public String getUserRolesQuery() {
        return userRolesQuery;
    }

    public void setUserRolesQuery(String userRolesQuery) {
        this.userRolesQuery = userRolesQuery;
    }

    public String getAuthenticationQuery() {
        return authenticationQuery;
    }

    public void setAuthenticationQuery(String authenticationQuery) {
        this.authenticationQuery = authenticationQuery;
    }

    public boolean isPermissionsLookupEnabled() {
        return permissionsLookupEnabled;
    }

    public void setPermissionsLookupEnabled(boolean permissionsLookupEnabled) {
        this.permissionsLookupEnabled = permissionsLookupEnabled;
    }

    public String getPermissionsQuery() {
        return permissionsQuery;
    }

    public void setPermissionsQuery(String permissionsQuery) {
        this.permissionsQuery = permissionsQuery;
    }
}`

and on application.properties file:

`wicket.external.shiro.enabled=true
wicket.external.shiro.authentication-query=SELECT password FROM [user] WHERE username = ? and enabled = 1
wicket.external.shiro.user-roles-query=SELECT role_name FROM user_roles WHERE username = ?`

Of course I'm only contemplating the JdbcRealm class, but this is just an example of configuration, could also be included in these configurations the type of Realm, PasswordMatcher, etc.

**Comment by MarcGiffing** [comment]
Your configuration proposal is too detailed. I see the following problems:

* Not everyone is using SQL Databases
* You proposed already table names which doesn't match the users one
* Your configuration proposal should be part of the Shiro web starter project
* A quick start like the one I provided did not work cause it needs a database (the most important one)

If we add too much detailed Shiro configuration here we have to adapt it in every release. And there is already a starter which should be extended.

**Comment by martin-g** [comment]
I agree that such properties should be in shiro-starter project.
This project should provide settings that makes the integration of Wicket with Shiro simpler. Anything Shiro specific should be in shiro-starter.

**Comment by mavortius** [comment]
Those settings are just examples. Of course, if JdbcRealm is not configured, its specific settings will not be used. I think we all agree that these settings should be in the shro-starter and not here. For now, I'll use the great example you provided as a starting point for configuring Shiro with Wicket.

**Comment by MarcGiffing** [comment]
https://issues.apache.org/jira/browse/SHIRO-618
