### ISSUE TITLE
Consider autoconfiguration, documentation or simplification for clustered environment

### ISSUE THREAD

**Issue by MarcGiffing** [MarcGiffing/wicket-spring-boot#99]
https://github.com/MarcGiffing/wicket-spring-boot-examples/tree/master/cluster

**Comment by MarcGiffing** [comment]
Any feedback is welcome!

**Comment by braunimmobilien** [comment]
I have problem to integrate hibernate search

**Comment by MarcGiffing** [comment]
What exactly is the problem? Is it Wicket related?

**Comment by braunimmobilien** [comment]
following configuration:
pom.xml parent:


<modelVersion>4.0.0</modelVersion>
<groupId>braunimmobilien</groupId>
<artifactId>project</artifactId>
<version>1.0.9-SNAPSHOT</version>
<packaging>pom</packaging>

<name>braunimmobilien Parent</name>
<parent>
    <groupId>com.giffing.wicket.spring.boot.starter</groupId>
    <artifactId>wicket-spring-boot-starter-parent</artifactId>
    <version>2.0.0</version>
</parent>

<modules>
<module>wicket-spring-boot-starter-example</module>
</modules>



pom.xml wicket-spring-boot-starter-example:

<modelVersion>4.0.0</modelVersion>
<artifactId>wicket-spring-boot-starter-example</artifactId>

<parent>
<groupId>braunimmobilien</groupId>
<artifactId>project</artifactId>
<version>1.0.9-SNAPSHOT</version>
<relativePath>..</relativePath>
</parent>

<name>Spring boot starter example</name>
<description>
An example project which uses the wicket-spring-boot-starter
autoconfiguration project
</description>

<properties>
<maven.deploy.skip>true</maven.deploy.skip>
</properties>

<dependencies>
<dependency>
  <groupId>org.hibernate</groupId>
  <artifactId>hibernate-search-orm</artifactId>
  <version>4.5.1.Final</version>
</dependency>
<dependency>
  <groupId>org.hibernate</groupId>
  <artifactId>hibernate-entitymanager</artifactId>
</dependency>

.........your dependencies


application.properties :

security.basic.enabled=false
wicket.stuff.datastore.hazelcast.enabled=false
core.resourcesettings.packageresourceguard.pattern=- +*.map
server.compression.enabled=true
management.port=8081
spring.jpa.hibernate.ddl-auto=none
liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.datasource.url=jdbc:mysql://localhost:3306/CountryData
spring.datasource.username=root
spring.datasource.password=Braun
spring.jpa.properties.hibernate.search.default.directory_provider=filesystem
spring.jpa.properties.hibernate.search.default.indexBase=/home/braun/development/java/java1.8/spring-boot-wicket/wicket-spring-boot-master-own/lucene/indexes/

mvn -X spring-boot:run

2017-06-07 21:02:39.309 ERROR 31585 --- [  restartedMain]
o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating
bean with name 'entityManagerFactory' defined in class path resource
[org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]:
Invocation of init method failed; nested exception is
java.lang.AbstractMethodError





2017-06-07 19:45 GMT+02:00 MarcGiffing <notifications@github.com>:

**Comment by martin-g** [comment]
This is not Wicket related issue so you should ask for help at Spring Boot forums - StackOverflow and/or Gitter!
The problem looks like incompatible versions of Hibernate and Hibernate-Search-ORM. Check your versions with `mvn dependency:tree`.

**Comment by braunimmobilien** [comment]
I was successful with wicket-spring-boot-starter-parent 2.0.0 and hibernate-search-orm 5.7.0.Final
At the moment i only upgrade my wicket application to spring boot. The latest hibernate-search doesn't have the same funtionality as before. I started with 3 applications after this success i will go on with your application.Still investigate the usage of spring-webflow angular2 and react-usage. the examples i started with all use spring boot

**Comment by braunimmobilien** [comment]
I try to use  <dependency>
            <groupId>de.agilecoders.wicket</groupId>
            <artifactId>wicket-bootstrap-core</artifactId>
            <version>${wicketBootstrapVersion}</version>
        </dependency>
        <dependency>
            <groupId>de.agilecoders.wicket</groupId>
            <artifactId>wicket-bootstrap-extensions</artifactId>
            <version>${wicketBootstrapVersion}</version>
        </dependency>
        <dependency>
            <groupId>de.agilecoders.wicket</groupId>
            <artifactId>wicket-bootstrap-themes</artifactId>
            <version>${wicketBootstrapVersion}</version>
        </dependency>-
but the de.agilecoders.wicket artifacts use maximum wicket 6.15 so that the de.agilecoders.wicket artifacts can not be used

**Comment by ursjoss** [comment]
@braunimmobilien What's your ${wicketBootstrapVersion}?

AFAIK 0.8.4 and 0.9.x stay with wicket 6. 0.10.x uses wicket 7 and 2.x goes along with wicket 8.

**Comment by braunimmobilien** [comment]
When i use 
<dependency>
    <groupId>de.agilecoders.wicket</groupId>
    <artifactId>wicket-bootstrap-core</artifactId>
    <version>2.0.0-M5</version>
</dependency>
and
<parent>
    <groupId>com.giffing.wicket.spring.boot.starter</groupId>
    <artifactId>wicket-spring-boot-starter-parent</artifactId>
    <version>2.0.0</version>
</parent>
i get in the tests the following error:
Caused by: org.springframework.beans.factory.BeanCreationException: Error
creating bean with name
'com.giffing.wicket.spring.boot.starter.app.verifier.WicketDependencyVersionChecker':
Invocation of init method failed; nested exception is
com.giffing.wicket.spring.boot.starter.app.verifier.WicketDependencyMismatchDetectedException



2017-06-11 19:33 GMT+02:00 Urs Joss <notifications@github.com>:

**Comment by martin-g** [comment]
@braunimmobilien Please create new issues for new problems/questions! These issue is for other topic!
